/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Player_registrationRouteImport } from './routes/player_registration'
import { Route as Player_profileRouteImport } from './routes/player_profile'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const Player_registrationRoute = Player_registrationRouteImport.update({
  id: '/player_registration',
  path: '/player_registration',
  getParentRoute: () => rootRouteImport,
} as any)
const Player_profileRoute = Player_profileRouteImport.update({
  id: '/player_profile',
  path: '/player_profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/club': typeof ClubRoute
  '/coach': typeof CoachRoute
  '/player': typeof PlayerRoute
  '/player_profile': typeof Player_profileRoute
  '/player_registration': typeof Player_registrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/club': typeof ClubRoute
  '/coach': typeof CoachRoute
  '/player': typeof PlayerRoute
  '/player_profile': typeof Player_profileRoute
  '/player_registration': typeof Player_registrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/club': typeof ClubRoute
  '/coach': typeof CoachRoute
  '/player': typeof PlayerRoute
  '/player_profile': typeof Player_profileRoute
  '/player_registration': typeof Player_registrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/club'
    | '/coach'
    | '/player'
    | '/player_profile'
    | '/player_registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/club'
    | '/coach'
    | '/player'
    | '/player_profile'
    | '/player_registration'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/club'
    | '/coach'
    | '/player'
    | '/player_profile'
    | '/player_registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  ClubRoute: typeof ClubRoute
  CoachRoute: typeof CoachRoute
  PlayerRoute: typeof PlayerRoute
  Player_profileRoute: typeof Player_profileRoute
  Player_registrationRoute: typeof Player_registrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player_registration': {
      id: '/player_registration'
      path: '/player_registration'
      fullPath: '/player_registration'
      preLoaderRoute: typeof Player_registrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player_profile': {
      id: '/player_profile'
      path: '/player_profile'
      fullPath: '/player_profile'
      preLoaderRoute: typeof Player_profileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  ClubRoute: ClubRoute,
  CoachRoute: CoachRoute,
  PlayerRoute: PlayerRoute,
  Player_profileRoute: Player_profileRoute,
  Player_registrationRoute: Player_registrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
